apiVersion: v1
kind: Pod
metadata:
  name: pod-sc
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volumes
          name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: pvc-2