apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume
          name: volumes
    - name: jenkins-container
      image: jenkins:alpine
      volumeMounts:
        - mountPath: /volume
          name: volumes
  volumes:
    - name: volumes
      hostPath:
        path: /home/volumes
        type: DirectoryOrCreate